version: '3.8'
services:
  app:
    build: .
    environment:
      NODE_ENV: production
      APPLICATION_PORT: 3000
      APPLICATION_VERSION: '1.0.0'
      DATABASE_URI: "mongodb://mongodb:27017/processDB"
      SWAGGER_TITLE: 'Extrator automático de processos'
      SWAGGER_DESCRIPTION: 'Extrator automático de processos'
      SWAGGER_DOCS: swagger
      SWAGGER_SERVER: http://localhost:3000
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - process-network
    links:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .docker/db_data:/data/db
    networks:
      - process-network

networks:
  process-network:
    driver: bridge
    name: process-network